[features]
seeds = true
skip-lint = false

[programs.localnet]
battle_royale_program = "EnLAsghi9Yp25djXr7o7RsGHQxXz8kcCpL6LnjGRmxEQ"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./tests/genesis/mpl_token_metadata.so"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./tests/keypairs/test.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test-finish = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/finishBattle.ts"
create-collection = "yarn run ts-node scripts/createTestCollection.ts"
